### ISSUE TITLE
Getting java.lang.ClassCastException in Ghidra 11.1.1

### ISSUE THREAD

**Issue by x4FF3** [huettenhain/dhrake#11]
Hi,

i stumbled over this project, as i was trying to look at a delphi binary. After loading the two scripts into the ScriptManager, i get following error message when i try to run DhrakeInit:

`Unable to load script: DhrakeInit.java
>   detail: Unexpected error: java.lang.ClassCastException: class ghidra.app.plugin.core.osgi.GhidraPlaceholderBundle cannot be cast to class ghidra.app.plugin.core.osgi.GhidraSourceBundle (ghidra.app.plugin.core.osgi.GhidraPlaceholderBundle and ghidra.app.plugin.core.osgi.GhidraSourceBundle are in unnamed module of loader ghidra.GhidraClassLoader @68f7aae2)
`
are there adjustments needed to be compatible with ghidra 11.1.1?

KR

**Comment by huettenhain** [comment]
It works just fine under Ghidra 11.1.1 for me. I'll have to assume you have some error in your setup; for the future please try to provide better information to reproduce a bug, otherwise the conversation is doomed to go like this one 😞.
