### ISSUE TITLE
Unable to run any of the scripts

### ISSUE THREAD

**Issue by shaperones0** [huettenhain/dhrake#9]
Scripts have been successfully added into Ghidra, so they appear in the script manager:
![image](https://github.com/huettenhain/dhrake/assets/86309764/e5d17953-84cb-4e11-981d-b877ae78fa0f)

However, running them doesn't do anything.
CodeBrowser's console contains only the following output:
![image](https://github.com/huettenhain/dhrake/assets/86309764/9f7643d0-8a68-4ed4-ac31-9380eaea3619)
```
> Unable to load script: DhrakeInit.java
>   detail: The class could not be found. It must be the public class of the .java file: DhrakeInit
```
Which is weird, since the file does contain the class and stuff (all parenthesis and similar are in right order) (see first screenshot)

**Comment by huettenhain** [comment]
Frankly, this does not sound like a problem with Dhrake specifically. Can you try to reproduce this with a simple script that does nothing? If you can, the problem is likely more general.

**Comment by shaperones0** [comment]
So, apparently the issue was in the fact that i put those into a separate folder (so there were only two files in it, those are being the scripts). After I moved the scripts to the ghidra_scripts directory, the issue was resolved.
